### ISSUE TITLE
Search example not working

### ISSUE THREAD

**Issue by vitorhenriquemaia** [asadamatic/firestore_search#1]
Hey Asad.

Thanks for sharing the package. I am trying to use the exemple from pub.dev and the search is not working 
When I type something, nothing happens and I don't get any error.

Can you give me a hand?

**Comment by asadamatic** [comment]
I have found the issue with my package and will fix it in the next build. 

One of the key argument was missing.

 `searchBy`  **Key for the `firestore_collection` value you want to search by**. 
 
 For example if you want the search queries to be compared to `username` field of user document in firestore_collection you should set it to **'username'**.

Thanks for reporting the bug :)

**Comment by asadamatic** [comment]
Update to `firestore_search : 0.0.6` to get rid of the issue.

**Comment by vitorhenriquemaia** [comment]
C:\src\flutter\flutter\bin\flutter.bat --no-color pub get
Running "flutter pub get" in nomadsyard_app...                  

Because firestore_search >=0.0.5 depends on cloud_firestore ^0.14.0 and nomadsyard_app depends on cloud_firestore ^0.16.0, firestore_search >=0.0.5 is forbidden.
So, because nomadsyard_app depends on firestore_search ^0.0.6, version solving failed.
pub get failed (1; So, because nomadsyard_app depends on firestore_search ^0.0.6, version solving failed.)
Process finished with exit code 1

**Comment by vitorhenriquemaia** [comment]
C:\src\flutter\flutter\bin\flutter.bat --no-color pub get
Running "flutter pub get" in nomadsyard_app...                  

Because firestore_search >=0.0.5 depends on cloud_firestore ^0.14.0 and flutter_app depends on cloud_firestore ^0.16.0, firestore_search >=0.0.5 is forbidden.
So, because nomadsyard_app depends on firestore_search ^0.0.6, version solving failed.
pub get failed (1; So, because flutter_app depends on firestore_search ^0.0.6, version solving failed.)
Process finished with exit code 1

**Comment by vitorhenriquemaia** [comment]
C:\src\flutter\flutter\bin\flutter.bat --no-color pub get
Running "flutter pub get" in flutter_app...

Because firestore_search >=0.0.5 depends on cloud_firestore ^0.14.0 and flutter_app depends on cloud_firestore ^0.16.0, firestore_search >=0.0.5 is forbidden.
So, because flutter_app depends on firestore_search ^0.0.6, version solving failed.
pub get failed (1; So, because flutter_app depends on firestore_search ^0.0.6, version solving failed.)
Process finished with exit code 1

**Comment by asadamatic** [comment]
Will fix it asap :)

**Comment by vitorhenriquemaia** [comment]
Alright, man!!! I'm waiting for it, it's so important for my project.

Thanks for your time!

**Comment by asadamatic** [comment]
Hi Vitor,

ALLHAMDULILLAH! I have fixed the issue with a new release.

Upgrade to firestore_search: ^0.0.7 to fix this issue.

Thanks :)
