### ISSUE TITLE
Example code not working

### ISSUE THREAD

**Issue by invincyx** [asadamatic/firestore_search#14]
Hello. I have been trying to  test your example code so i add the search function to my app but it seems the example code isn't working

**Comment by asadamatic** [comment]
Can you please highlight the exact error you're facing?
Here's a live web demo of the package and it seems to be working fine,
[Live Web Demo](https://firestore-search-pub.web.app/#/)

**Comment by invincyx** [comment]
![Screenshot_20211223-154300](https://user-images.githubusercontent.com/40611131/147249368-0e23f24c-c097-403f-8664-07034b6f5c61.jpg)
After running the code and trying to search it doesn't show any results as above.

Here is my firstore structure

![Screenshot 2021-12-23 at 15-42-08 Lit Files – Cloud Firestore – Firebase console](https://user-images.githubusercontent.com/40611131/147249500-ba384b51-8c45-4f1f-8dc5-23a385123ede.png)

The code 

```
FirestoreSearchScaffold(
      firestoreCollectionName: 'files',
      searchBy: 'name',
      scaffoldBody: const Center(child: Text('Firestore Search')),
      dataListFromSnapshot: DataModel().dataListFromSnapshot,
      builder: (context, snapshot) {
        if (snapshot.hasData) {
          final List<DataModel>? dataList = snapshot.data;

          return ListView.builder(
              itemCount: dataList?.length ?? 0,
              itemBuilder: (context, index) {
                final DataModel data = dataList![index];

                return Column(
                  mainAxisSize: MainAxisSize.min,
                  mainAxisAlignment: MainAxisAlignment.center,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Padding(
                      padding: const EdgeInsets.all(8.0),
                      child: Text(
                        '${data.name}',
                        style: Theme.of(context).textTheme.headline6,
                      ),
                    ),
                    Padding(
                      padding: const EdgeInsets.only(
                          bottom: 8.0, left: 8.0, right: 8.0),
                      child: Text('${data.name}',
                          style: Theme.of(context).textTheme.bodyText1),
                    )
                  ],
                );
              });
        }

        if (snapshot.connectionState == ConnectionState.done) {
          if (!snapshot.hasData) {
            return const Center(
              child: Text('No Results Returned'),
            );
          }
        }
        return const Center(
          child: CircularProgressIndicator(),
        );
      },
    );
```

The Model

```
class DataModel {
  final String? name;
  final String? link;
  // final String? framework;
  // final String? tool;

  DataModel({this.name, this.link});

  //Create a method to convert QuerySnapshot from Cloud Firestore to a list of objects of this DataModel
  //This function in essential to the working of FirestoreSearchScaffold

  List<DataModel> dataListFromSnapshot(QuerySnapshot querySnapshot) {
    return querySnapshot.docs.map((snapshot) {
      final Map<String, dynamic> dataMap =
          snapshot.data() as Map<String, dynamic>;

      return DataModel(
        name: dataMap['name'],
        link: dataMap['link'],
      );
      // framework: dataMap['framework'],
      // tool: dataMap['tool']);
    }).toList();
  }
}
```

**Comment by invincyx** [comment]
I'm using these
```
firebase_core: ^1.10.6
cloud_firestore: ^2.2.2
firestore_search: ^0.1.7
```

**Comment by asadamatic** [comment]
Have you configured firebase for your project?

**Comment by invincyx** [comment]
yes, Firebase is configured and everything firebase related is working.
I'm just having issues with the search.

![Screenshot 2021-12-23 at 19 34 05](https://user-images.githubusercontent.com/40611131/147274584-f63c33c4-1958-491d-b7f2-5ad41f3108d0.png)

**Comment by invincyx** [comment]
![image](https://user-images.githubusercontent.com/40611131/147274860-c7cca4d1-ebc0-401b-94ce-8fbd01fa5ac2.png)

on your web example, can I have a few search terms in your database so I can  see

**Comment by asadamatic** [comment]
The issue might be that your configured firebase project does not have any
entries in the cloudfirestore.

Lemme share a screenshot of the collection so you can replicate it.

**Comment by asadamatic** [comment]
![Screenshot_20211223_224518](https://user-images.githubusercontent.com/37589169/147275702-440e2d89-0cd1-4618-aa5c-2166cf344f80.jpg)

**Comment by invincyx** [comment]
Thanks. The issue was with my firestore entries structure
