### ISSUE TITLE
Search bar testing. 

### ISSUE THREAD

**Issue by Marchel0925** [asadamatic/firestore_search#17]
Hallo. I need some examples of how to test the search bar.

When I write some text in the search bar using WidgetTester enterText() method, and use pumpAndSettle() the whole integration test freezes.

Is there even testing support for this package? 

How do I enter text and check the result?

Thank you.

**Comment by asadamatic** [comment]
@Marchel0925 You have to add some data in `Cloud Firestore` and create a corresponding class. You will need to create a function that converts `Data Snapshot` to Your object. You can see this implementation [here](https://pub.dev/packages/firestore_search#:~:text=create%20a%20data%20model%2C%20for%20the%20data%20you%20want%20retrieve).

**Comment by Marchel0925** [comment]
I'm afraid that's not the case. The database that I'm using has data and when running the project, all seems to go well. The data is filtered | searched correctly. But when I try to do the same with integration tests ->

await tester.enterText(find.byType(FirestoreSearchBar), "some_uid");
await tester.pumpAndSettle();

The whole integration test freezes, like it does not know what to do.

The result when doing manual testing is there (filtered list).

**Comment by asadamatic** [comment]
Testing is not supported for this package.
