### ISSUE TITLE
Searchbar

### ISSUE THREAD

**Issue by Abdullah291** [asadamatic/firestore_search#2]
i have one more suggestion how can change this i have app bar consist of two things one is leading title and second is  trailing search icon when i click search icon the app bar change into the search bar then i search .

**Comment by asadamatic** [comment]
Thanks for your suggestion, I will try to add this feature in future updates.

I'll be working on this feature soon :)

**Comment by asadamatic** [comment]
@Abdullah291 Added the requested functionality in the new release.

1. Update to `firestore_search: ^0.0.8`
2. Set parameter `showSearchButton` equal to `true`.

If you find this package helpful consider giving a thumbs-up  and star the repo 🙂
